// <auto-generated />
using System;
using Invoria.Reporting.Infrastructure.EntityFramework;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Invoria.Reporting.Infrastructure.EntityFramework.Migrations
{
    [DbContext(typeof(ReportingDbContext))]
    [Migration("20260514134825_OrderPeriodSummaryRollup")]
    partial class OrderPeriodSummaryRollup
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Invoria.Reporting.Domain.Orders.OrderPeriodSummary.OrderPeriodSummary", b =>
                {
                    b.Property<string>("Granularity")
                        .HasMaxLength(16)
                        .HasColumnType("nvarchar(16)");

                    b.Property<string>("PeriodKey")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<int>("DateField")
                        .HasColumnType("int");

                    b.Property<int>("CancelledCount")
                        .HasColumnType("int");

                    b.Property<int>("DeliveredCount")
                        .HasColumnType("int");

                    b.Property<decimal>("DiscountAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("GrossRevenue")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("NetRevenue")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("OrderCount")
                        .HasColumnType("int");

                    b.Property<DateOnly>("PeriodEnd")
                        .HasColumnType("date");

                    b.Property<DateOnly>("PeriodStart")
                        .HasColumnType("date");

                    b.HasKey("Granularity", "PeriodKey", "DateField");

                    b.HasIndex("DateField", "Granularity", "PeriodStart");

                    b.ToTable("OrderPeriodSummary", (string)null);
                });

            modelBuilder.Entity("Invoria.Reporting.Domain.Orders.ReportedOrder", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<decimal>("AmountOutstanding")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("AmountPaid")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("CustomerId")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<int>("FullfillmentStatus")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset?>("LastModifiedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("LastModifiedBy")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("OrderNumber")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<int>("OrderStatus")
                        .HasColumnType("int");

                    b.Property<int>("PaymentStatus")
                        .HasColumnType("int");

                    b.Property<int>("PaymentType")
                        .HasColumnType("int");

                    b.Property<long>("ReplicationVersion")
                        .HasColumnType("bigint");

                    b.Property<DateTimeOffset?>("SourceLastKnownAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<decimal>("TotalOrderAmount")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("CustomerId");

                    b.ToTable("ReportedOrder", (string)null);
                });

            modelBuilder.Entity("Invoria.Reporting.Domain.Orders.ReportedOrderFailureDetail", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("ItemId")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<DateTimeOffset?>("LastModifiedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("LastModifiedBy")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<int>("QuantityAvailable")
                        .HasColumnType("int");

                    b.Property<int>("QuantityRequested")
                        .HasColumnType("int");

                    b.Property<string>("ReportedOrderId")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<int>("Shortage")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ItemId");

                    b.HasIndex("ReportedOrderId");

                    b.ToTable("ReportedOrderFailureDetail", (string)null);
                });

            modelBuilder.Entity("Invoria.Reporting.Domain.Orders.ReportedOrderLine", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<decimal>("LineTotal")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("ProductId")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<string>("ReportedOrderId")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<decimal>("UnitPrice")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.HasIndex("ReportedOrderId");

                    b.ToTable("ReportedOrderLine", (string)null);
                });

            modelBuilder.Entity("Invoria.Reporting.Domain.Orders.ReportedOrderPayment", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<DateTimeOffset?>("LastModifiedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("LastModifiedBy")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<decimal>("PaidAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTimeOffset>("PaidAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<int>("PaymentMethod")
                        .HasColumnType("int");

                    b.Property<string>("ReportedOrderId")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("ReportedOrderId");

                    b.ToTable("ReportedOrderPayment", (string)null);
                });

            modelBuilder.Entity("Invoria.Reporting.Domain.Orders.ReportedOrderStateTransition", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<DateTimeOffset>("ChangedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<int>("FromFullfillmentStatus")
                        .HasColumnType("int");

                    b.Property<int>("FromStatus")
                        .HasColumnType("int");

                    b.Property<string>("Reason")
                        .HasMaxLength(1024)
                        .HasColumnType("nvarchar(1024)");

                    b.Property<string>("ReportedOrderId")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<int>("ToFullfillmentStatus")
                        .HasColumnType("int");

                    b.Property<int>("ToStatus")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ChangedAt");

                    b.HasIndex("ReportedOrderId");

                    b.ToTable("ReportedOrderStateTransition", (string)null);
                });

            modelBuilder.Entity("Invoria.Reporting.Domain.Orders.StatusSummary.ReportedOrderStatusByDay", b =>
                {
                    b.Property<DateOnly>("DayUtc")
                        .HasColumnType("date");

                    b.Property<int>("OrderStatus")
                        .HasColumnType("int");

                    b.Property<int>("Count")
                        .HasColumnType("int");

                    b.HasKey("DayUtc", "OrderStatus");

                    b.ToTable("ReportedOrderStatusByDay", (string)null);
                });

            modelBuilder.Entity("Invoria.Reporting.Domain.Orders.ReportedOrderFailureDetail", b =>
                {
                    b.HasOne("Invoria.Reporting.Domain.Orders.ReportedOrder", "ReportedOrder")
                        .WithMany("FailureDetails")
                        .HasForeignKey("ReportedOrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ReportedOrder");
                });

            modelBuilder.Entity("Invoria.Reporting.Domain.Orders.ReportedOrderLine", b =>
                {
                    b.HasOne("Invoria.Reporting.Domain.Orders.ReportedOrder", "ReportedOrder")
                        .WithMany("Lines")
                        .HasForeignKey("ReportedOrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ReportedOrder");
                });

            modelBuilder.Entity("Invoria.Reporting.Domain.Orders.ReportedOrderPayment", b =>
                {
                    b.HasOne("Invoria.Reporting.Domain.Orders.ReportedOrder", "ReportedOrder")
                        .WithMany("Payments")
                        .HasForeignKey("ReportedOrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ReportedOrder");
                });

            modelBuilder.Entity("Invoria.Reporting.Domain.Orders.ReportedOrderStateTransition", b =>
                {
                    b.HasOne("Invoria.Reporting.Domain.Orders.ReportedOrder", "ReportedOrder")
                        .WithMany("StateTransitions")
                        .HasForeignKey("ReportedOrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ReportedOrder");
                });

            modelBuilder.Entity("Invoria.Reporting.Domain.Orders.ReportedOrder", b =>
                {
                    b.Navigation("FailureDetails");

                    b.Navigation("Lines");

                    b.Navigation("Payments");

                    b.Navigation("StateTransitions");
                });
#pragma warning restore 612, 618
        }
    }
}
