name: Deploy to MonsterASP

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  deploy:
    runs-on: windows-latest
    timeout-minutes: 20

    env:
      API_PROJECT: src/Invoria.Api/Invoria.Api.csproj
      PUBLISH_DIR: publish
      PROD_WEBSITE_NAME: ${{ secrets.PROD_WEBSITE_NAME }}
      PROD_SERVER_COMPUTER_NAME: ${{ secrets.PROD_SERVER_COMPUTER_NAME }}
      PROD_SERVER_USERNAME: ${{ secrets.PROD_SERVER_USERNAME }}
      PROD_SERVER_PASSWORD: ${{ secrets.PROD_SERVER_PASSWORD }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Restore
        run: dotnet restore $env:API_PROJECT

      - name: Publish
        run: dotnet publish $env:API_PROJECT -c Release -o $env:PUBLISH_DIR /p:UseAppHost=false --runtime win-x86 

      - name: Deploy via FTP
        uses: SamKirkland/FTP-Deploy-Action@v4.3.4
        with:
          server: ${{ secrets.PROD_FTP_SERVER }}
          username: ${{ secrets.PROD_FTP_USERNAME }}
          password: ${{ secrets.PROD_FTP_PASSWORD }}
          local-dir: ./publish/
          server-dir: /wwwroot/
